# Generated by Django 4.0.1 on 2024-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watch',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.Watchlist'),
        ),
    ]
