# Generated by Django 4.0.1 on 2024-01-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_delete_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidlist',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='bidlists', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
