# Generated by Django 4.0.1 on 2024-02-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='postlikes',
        ),
    ]
