# Generated by Django 4.0.1 on 2024-02-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amphure',
            name='province_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='amphure_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='province',
            name='geography_id',
            field=models.CharField(max_length=255),
        ),
    ]
