# Generated by Django 4.0.1 on 2024-02-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_amphure_province_id_alter_district_amphure_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geography',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.RemoveField(
            model_name='location',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='province',
            name='code',
        ),
        migrations.RemoveField(
            model_name='province',
            name='geography_id',
        ),
        migrations.RemoveField(
            model_name='province',
            name='name_th',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='province',
            table=None,
        ),
        migrations.DeleteModel(
            name='Amphure',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
