# Generated by Django 4.0.1 on 2024-02-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_delete_geography_remove_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='breed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='pet.breed'),
        ),
    ]
