# Generated by Django 4.0.1 on 2024-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_user_url_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='topic',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
